// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwrolqjgtfrymonjaqgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3cm9scWpndGZyeW1vbmphcWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTk5NTUsImV4cCI6MjA3MTQzNTk1NX0.FBtDI0UOL9im5KxTN9GLPDP6XMQqei-Te48dEJn7H5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});